services:
  wordpress:
    image: wordpress:latest
    restart: $AUTO_RESTART
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - ./_wordpress:/var/www/html
      - ./azwp-mailer:/var/www/html/wp-content/plugins/azwp-mailer
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: $AUTO_RESTART
    environment:
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./_db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: $AUTO_RESTART
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - db
